module.exports = {
    labaemc: [
        'intro',
        {
            type: 'category',
            label: 'Before you begin',
            items: [{
                type: 'autogenerated',
                dirName: '10-Before-you-begin',
            }, ],
        },

        {
            type: 'category',
            label: 'Implementation',
            items: [{
                type: 'autogenerated',
                dirName: '20-Implementation',
            }, ],
        },

        {
            type: 'category',
            label: 'Simulation',
            items: [{
                type: 'autogenerated',
                dirName: '30-Simulation',
            }, ],
        },

        {
            type: 'category',
            label: 'Additional Content',
            items: [{
                type: 'autogenerated',
                dirName: '99-Additional-Content',
            }, ],
        },

        {
            type: 'link',
            label: 'Post Lab Survey',
            href: 'https://crewteam.service-now.com/esc?id=workshop_survey&type_id=ff8cc99e877d21106af8ec6e0ebb3546',
        },
    ],
};