// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    teleworkvancouver: [

        {
            type: 'category',
            label: 'Telework Case Management',
            items: [
                '0.0-introduction/overview',
                '0.0-introduction/use-case',
                '0.0-introduction/planning',
                '0.0-introduction/takeoff',
            ],
        },

        {
            type: 'category',
            label: '1. Build the Foundation',
            items: [
                '1.0-Build-the-Foundation/overview',
                '1.0-Build-the-Foundation/create-app',
                '1.0-Build-the-Foundation/create-arrangement-table',
                '1.0-Build-the-Foundation/create-telework-case-table',
                '1.0-Build-the-Foundation/data-in-table-builder',
                '1.0-Build-the-Foundation/configure-telework-form',
                '1.0-Build-the-Foundation/forms-in-table-builder',
            ],
        },

        {
            type: 'category',
            label: '2. Create the User Experience',
            items: [
                '2.0-The-User-Experience/overview',
                '2.0-The-User-Experience/create-form',
            ],
        },

        {
            type: 'category',
            label: '3. Automate Work',
            items: [
                '3.0-Automate-Work/overview',
                '3.0-Automate-Work/create-workflow',
                '3.0-Automate-Work/test-workflow',
            ],
        },

        {
            type: 'category',
            label: '4. Manage the Work',
            items: [
                '4.0-Manage-Work/overview',
                '4.0-Manage-Work/create-workspace',
                '4.0-Manage-Work/configure-workspace',
                '4.0-Manage-Work/use-workspace',
            ],
        },

        {
            type: 'category',
            label: 'Conclusion',
            items: [
                '5.0-conclusion/lab-review',
                '5.0-conclusion/resources',
                '5.0-conclusion/appendix',
            ],
        },

        'changelog',
        'lab-guide-pdf',

        /*
        { 
            type: "autogenerated", 
            dirName: "telework-utah" 
        }
        */
    ],
};

module.exports = sidebars;
