// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    labcomplaint: {
        'Get started': [
            'overview',
            'audience',
            'definitions',
        ],

        '1. Agent Workspace': [
            'exercise_1_workspace/overview',
            'exercise_1_workspace/configure',
            'exercise_1_workspace/available',
        ],
        '2. Complaint Management': [
            'exercise_2_demo/overview',
            'exercise_2_demo/portal',
            'exercise_2_demo/agent',
        ],
        '3. Reporting': [
            'exercise_3_reporting/overview',
            'exercise_3_reporting/insights',
        ],
        '4. Scale Digital Innovation ': [
            'exercise_4_customize/overview',
            'exercise_4_customize/configure',
        ],

        '5. Create with App Engine': [
            'exercise_5-build/overview',
            'exercise_5-build/apply',
            'exercise_5-build/create',
            'exercise_5-build/data-model',
            'exercise_5-build/workspace',
            'exercise_5-build/automation',
        ],

        'Review': [
            'review',
        ],

    }

    /*
        'Get started': [
            'overview',
            'usecaseoverview',
        ],
        
        '1. Agent Workspace': [
            'exercise_1/overview',
            'exercise_1/configure',
        ],
        
        '2. Complaint App Demo': [
            'exercise_2/overview',
            'exercise_2/csm-portal',
            'exercise_2/csm-agent',
        ],

        '3. Configure Complaint App': [
            'exercise_3/overview',
            'exercise_3/configure-form',
            'exercise_3/configure-playbook',
        ],

        '4. Create Investigations App': [
            'exercise_4/overview',
            'exercise_4/create-app',
            'exercise_4/create-data-model',
        ],

        '5. Create with App Engine': [
            'exercise_5-build/overview',
            'exercise_5-build/apply',
            'exercise_5-build/create',
        ],

        'Review': [
            'review',
        ],
    */

    // labcomplaint: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;