// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    labcomplaint: {
        'Get started': [
            'overview',
        ],

        '5. Create with App Engine': [
            'exercise_5-build/overview',
            'exercise_5-build/apply',
            'exercise_5-build/create',
            'exercise_5-build/data-model',
            'exercise_5-build/workspace',
        ],

        'Review': [
            'review',
        ],

    }

    /*
        'Get started': [
            'overview',
            'usecaseoverview',
        ],
        
        '1. Agent Workspace': [
            'exercise_1/overview',
            'exercise_1/configure',
        ],
        
        '2. Complaint App Demo': [
            'exercise_2/overview',
            'exercise_2/csm-portal',
            'exercise_2/csm-agent',
        ],

        '3. Configure Complaint App': [
            'exercise_3/overview',
            'exercise_3/configure-form',
            'exercise_3/configure-playbook',
        ],

        '4. Create Investigations App': [
            'exercise_4/overview',
            'exercise_4/create-app',
            'exercise_4/create-data-model',
        ],

        '5. Create with App Engine': [
            'exercise_5-build/overview',
            'exercise_5-build/apply',
            'exercise_5-build/create',
        ],

        'Review': [
            'review',
        ],
    */

    // labcomplaint: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;