name: Generate PDFs

on:
    workflow_run:
        workflows: ["pages-build-deployment"]
        types: 
        - completed

jobs:
    generate_pdfs:
    runs-on: ubuntu-latest
    steps:

    - name: Install Prince
    run: |
        curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
        tar zxf prince-14.2-linux-generic-x86_64.tar.gz
        cd prince-14.2-linux-generic-x86_64
        yes "" | sudo ./install.sh

    - name: Build Collaborate Lab PDF
    run: npx docusaurus-prince-pdf -u https://creatorworkflowsnow.github.io/labs/collaborate/get_started/intro/ --output 'build/labs/collaborate/collaborate-lab.pdf'

    - name: Build Travel Request Lab PDF
    run: npx docusaurus-prince-pdf -u https://creatorworkflowsnow.github.io/labs/travelrequest/introduction/ --output 'build/labs/travelrequest/travel-request-lab.pdf'

    - name: Commit and Push PDFs
    run: |
        git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --local user.name "${{ secrets.GIT_USER_NAME }}"
        git add labs/collaborate/collaborate-lab.pdf labs/travelrequest/travel-request-lab.pdf
        git commit -m "Add generated PDFs"
        git push origin gh-pages
    env:
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}