name: source-build-and-deploy

on:
  push:
    branches:
    - source
  # paths:
  # - '!.github/**' # Ignore changes in '.github/' directory
    - '!labs/collaborate/creatorworkflowsnow.github.io-labs-collaborate.pdf'
  # Review gh actions docs if you want to further define triggers, paths, etc
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  source-build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 20.5.1
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: NPM Start
        run: npm start &

      - name: Wait for NPM to start
        run: wait $!

      - name: Install Prince
        run: |
          curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
          tar zxf prince-14.2-linux-generic-x86_64.tar.gz
          cd prince-14.2-linux-generic-x86_64
          yes "" | sudo ./install.sh

      - name: Build Collaborate Lab PDF
#       run: npx docusaurus-prince-pdf -u https://creatorworkflowsnow.github.io/labs/collaborate/get_started/intro/ --output 'labs/collaborate/creatorworkflowsnow.github.io-labs-collaborate.pdf'
        run: npx docusaurus-prince-pdf -u http://localhost:3000/labs/collaborate/get_started/intro/ --output 'labs/collaborate/collaborate-lab.pdf'

      - name: Build Trave Request Lab PDF
        run: npx docusaurus-prince-pdf -u http://http://localhost:3000/labs/travelrequest/introduction/ --output 'labs/travelrequest/travel-request-lab.pdf'

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurusk
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_AUTH_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
